version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-ap44
    volumes:
      - ./server:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/dhparam:/etc/nginx/dhparam
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/etc/nginx/letsencrypt
    environment: 
      BASE_URI: ${SERVER_URI}
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      server-network:
        ipv4_address: 172.40.0.3

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/etc/nginx/letsencrypt -email=${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ap44server.duckdns.org -d www.ap44server.duckdns.org
    volumes: 
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/logs:/var/logs/letsencrypt
      - ./certbot/data:/etc/nginx/letsencrypt
    networks:
      server-network:
        ipv4_address: 172.40.0.4
  

networks:
    server-network:
        external: true
        name: server-containers