version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-ap44
    volumes:
      - ./server:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/dhparam:/etc/nginx/dhparam
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/etc/letsencrypt
    environment: 
      BASE_URI: ${SERVER_URI}
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on: 
      - "certbot"
    networks:
      server-network:
        ipv4_address: 172.40.0.3

  certbot:
    image: infinityofspace/certbot_dns_duckdns
    container_name: nginx-certbot
    command: "certonly --non-interactive --agree-tos --email ${CERTBOT_EMAIL} --preferred-challenges dns --authenticator dns-duckdns --dns-duckdns-token ${DUCKDNS_TOKEN} --dns-duckdns-propagation-seconds 90 -d ${SERVER_URI}"
    volumes: 
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/etc/letsencrypt
    networks:
      server-network:
        ipv4_address: 172.40.0.4
  

networks:
    server-network:
        external: true
        name: server-containers